name: Qodana - PhpUnit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload

      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-clover ./.qodana/code-coverage/coverage.xml
        env:
          XDEBUG_MODE: coverage

      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: php-coverage-data
          path: ./.qodana/code-coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "-i,PHP/phpunit,--linter,jetbrains/qodana-php:2023.2-eap"
          pr-mode: false